export default function translater_enemy (text, trans) {
   if (text == undefined) {
      return (
         ""
      )
   } else {
      var replacement = text
         .toString()
         .replace(/(：)(.{1,99})(対するカウンター)/gm, "$1$3$2")
         .replace(/(：)(.*)(よりも)(.*)(\n)(\s+)(自身の)(.*)/gm, "$1$7$8 $3$2")

      replacement= replacement.toString().replace(/「/gm, " |").replace(/」/gm, "| ").replace(/・(.*)：/gm, "• |$1|: ").split("|")
      replacement.map((self, i) => {
         var replace = trans[self.replace(/<BRV>/gm, "BRV").replace(/<HP>/gm, "HP")]
         if (replace == undefined) {
            replace = trans[self.replace(/<BRV>/gm, "ブレイブ")]
         }
         if (replace != undefined) {
            replacement[i] = `${replace}`
         }
      })
      replacement = replacement.join("")
      /*eslint no-irregular-whitespace: ["error", { "skipRegExps": true }]*/
      replacement =
         replacement.toString()
            .replace(/消費BRV減少 の効果が発動したとき\n(　*|　*\s　*|　*\s*)HP攻撃後に保持できるBRVの上限が\n(　*|　*\s　*|　*\s*)自身の所持できるBRV上限の(\d+)%までになる/gm, "limit of BRV retained after <HP> attack becomes $3% of own held bravery limit when Reduced BRV Consumption effect triggered")
            .replace(/※ただし自身が以下のアビリティを使用する度に 自身のHPの下限値が(\d*.*)に減少/gm, "*The lower limit of HP becomes $1 on the turn after one of the following abilities have been used")
            .replace(/自身のHPが(.*)未満時に使用/gm, "Used when HP less than $1 of MAX")
            .replace(/敵全体の強化効果 自身の弱体効果を全て解除/gm, "removes all enemies' buffs, own debuffs")
            .replace(/対象の強化効果 自身の弱体効果を全て解除/gm, "Cancels targets buffs; removes own debuffs")
            .replace(/自身の弱体効果を全て解除し/gm, "Removes own debuffs")
            .replace(/自身の弱体効果を全て解除/gm, "Removes own debuffs")
            .replace(/フォースタイム (\d+)ACTION/gm, "force time for $1 turns")
            .replace(/自身の弱体効果 敵全体の強化効果を全て解除/gm, "Removes own debuffs and removes all targets' buffs")
            .replace(/敵全体の強化効果を全て解除し/gm, "removes all targets' buffs")
            .replace(/敵全体の強化効果を全て解除/gm, "removes all targets' buffs")
            .replace(/自身の弱体効果をすべて解除/gm, "Removes all debuffs")
            .replace(/対象の強化効果を全て解除し/gm, "Removes targets buffs")
            .replace(/対象の強化効果を全て解除/gm, "Removes targets buffs")
            .replace(/自身のブレイク状態を回復し/gm, "Recovers from Break")
            .replace(/ブレイク状態を回復し/gm, "Recovers from Break")
            .replace(/自身行動時　(\d*)%増加/gm, "$1% increase on own action")
            .replace(/プレイヤー行動時 (\d+)%増加/gm, "$1% increase on player action")
            .replace(/バトル開始時から以下条件で フォースゲージが増減する/gm, "Force gauge fills per following conditions from start of battle:")
            .replace(/与えるHPダメージはHP軽減・無効効果は無視しない/gm, "does not ignore effects that resist, nullify HP damage")
            .replace(/ {2}/gm, " ")
            .replace(/敵全員のHPを現在HPの(\d+)%にする<HP>攻撃/gm, "<HP> attack that reduces all enemies' HP to $1% of current HP")
            .replace(/所持BRV上限が99999を突破（(\d+)まで）/gm, "held bravery may exceed limit of 99999 (up to $1)")
            .replace(/キャラクターのBRV回復効果が(\d*)%軽減される/gm, "reduces player party's BRV recovery effects by $1%")
            .replace(/バトル開始時からHP(\d*)%の間 フォースゲージチャージスピードが(\d*|\d*\.\d*)倍/gm, "Start of battle–$1% HP: Force gauge charge speed × $2")
            .replace(/HP(\d*)%からHP(\d*)%の間 フォースゲージチャージスピードが(\d*|\d*\.\d*)倍/gm, "$1%–$2% HP: Force gauge charge speed × $3")
            .replace(/HP(\d*)%未満の時 フォースゲージチャージスピードが(\d+|\d+\.\d+)倍/gm, "Less than $1% HP: Force gauge charge speed × $2")
            .replace(/※複数体が異なる条件を満たす時 効果値の高い方が優先される/gm, "*Higher value takes precedence when multiple enemies meet different conditions")
            .replace(/受けるBRVダメージを(\d*)%軽減する/gm, "reduces BRV damage taken by $1%")
            .replace(/HPが(\d+)%未満にならない/gm, "HP cannot fall below $1%")
            .replace(/BRVが最大BRVの(\d+)%未満にならない/gm, "BRV cannot fall below $1% of MAX BRV")
            .replace(/与えるBRVダメージ上限が(\d+)を(\d+)%分突破可能（(\d+)まで）/gm, "BRV damage dealt can exceed limit of $1 (up to $3)")
            .replace(/所持できるBRV上限の(\d+)%までしか加算できなくなる/gm, "BRV gain limited to $1% of held bravery limit")
            .replace(/所持できるBRV上限の(\d+)％までしか加算できなくなる/gm, "BRV gain limited to $1% of held bravery limit")
            .replace(/与えるBRVダメージ上限が9999を(\d+)％分突破可能（(\d+)まで）/gm, "BRV damage dealt can exceed limit of 9999 (up to $2)")
            .replace(/与えるBRV HPダメージは BRV HP軽減 無効効果を無視する/gm, "ignores effects that reduce, nullify BRV, HP damage")
            .replace(/HP攻撃後に保持できるBRVの上限が.*\n.*自身の所持できるBRV上限の(\d+)％までになる/gm, "BRV retained limited to $1% of held bravery limit")
            .replace(/ (Unused)/gm, "")
            .replace(/全体近距離物理/gm, "Group Melee")
            .replace(/全体遠距離物理/gm, "Group Ranged")
            .replace(/全体魔法/gm, "Group Magic")
            .replace(/>攻撃/gm, "> attack")
            .replace(/> 属性/gm, "> ")
            .replace(/>属性/gm, "> ")
            .replace(/はバーストモード中 召喚中以外では必ず発動/gm, "is always activated except during burst mode and summoning")
            .replace(/弱体効果にかからない/gm, "Debuff immunity")
            .replace(/バトル開始時から以下条件で フォースゲージが増加する/gm, "Force gauge fills per following conditions from start of battle:")
            .replace(/自身が下記の状態になる/gm, "gains following effects")
            .replace(/【増加条件】/gm, "[Increase]")
            .replace(/【減少条件】/gm, "[Decrease]")
            .replace(/吹きとばない/gm, "Cannot knock back")
            .replace(/ブレイク状態を回復/gm, "Recovers from Break")
            .replace(/倒せない/gm, "Cannot be KO'd")
            .replace(/行動負荷が高い/gm, "low turn rate")
            .replace(/キャラクターの行動順に割り込む/gm, "Inserts self in between player party turns")
            .replace(/弱体効果が付与された対象に より大きなBRVダメージ/gm, "deals extra BRV damage to debuffed targets")
            .replace(/※この攻撃で敵全体を戦闘不能にできなかった場合 特殊カウントを再付与する/gm, "*special countdown resets if this attack fails to KO all enemies")
            .replace(/BRV軽減 無効効果を無視する/gm, "ignores effects that resist, nullify BRV damage")
            .replace(/対象の行動順を1つ遅らせる/gm, "delays target 1 turn")
            .replace(/対象の行動順を2つ遅らせる/gm, "delays target 2 turns")
            .replace(/使用後2回の行動で自身の行動負荷がなくなる/gm, "instant turn rate for second turn after use")
            .replace(/使用後1回の行動で自身の行動負荷がなくなる/gm, "instant own turn rate for 1 turn after use")
            .replace(/与えたHPダメージに応じて自身のHP回復/gm, "Recovers own HP depending on HP damage dealt")
            .replace(/行動後に自身のBRVを加算する/gm, "Increases BRV after turn")
            .replace(/与えるHPダメージは等倍/gm, "deals total HP damage to each target")
            .replace(/与えるHPダメージは分配/gm, "Deals proportionate HP damage to each target")
            .replace(/自身の初期BRVに応じて 自身のBRVを加算後/gm, "Increases BRV based on own INT BRV")
            .replace(/対象をブレイク時 行動順を2つ遅らせる/gm, "delays target 2 turns when inflicting Break")
            .replace(/自身の攻撃力・防御力・素早さをアップ/gm, "raises ATK, DEF, SPD")
            .replace(/甲羅に入った状態となり/gm, "Hides in shell")
            .replace(/浮遊中のみ使用/gm, "Only used while levitating")
            .replace(/使用後 着地する/gm, "touches down after use")
            .replace(/一定量のHPダメージを無効化する状態になる/gm, "Becomes immune to certain amount of HP damage")
            .replace(/自身の行動順を自身の直後に移動させる/gm, "Moves own turn to follow own turn")
            .replace(/特殊カウントを再付与する/gm, "Re-grant special count")
            .replace(/行動順を遅らせられない/gm, "Can not be delayed")
            .replace(/ブレイクによる行動順遅延のみ無効/gm, "Cannot be delayed from Break")
            .replace(/自身の攻撃力と防御力と最大BRVをアップ/gm, "raises ATK, DEF, MAX BRV")
            .replace(/受けるBRVダメージ HPダメージを軽減するようになり/gm, "BRV and HP damage received is now reduced")
            .replace(/キャラクターが行動時 HPダメージが発生するようになる/gm, "HP damage will now occur when a character acts")
            .replace(/対象の行動順を6つ遅らせる/gm, "Delays target by 6 turns")
            .replace(/対象をブレイク時 ブレイク中攻撃時 行動負荷ダウン/gm, "higher turn rate when inflicting Break or attacking target afflicted with Break")
            .replace(/味方全員の攻撃力・防御力・素早さ・最大BRV・初期BRVをアップ/gm, "raises ATK, DEF, SPD, MAX BRV, INT BRV of all allies")
            .replace(/自身の攻撃力・素早さ・初期BRV・最大BRVをアップする/gm, "raises ATK, SPD, INT BRV, MAX BRV")
            .replace(/攻撃力と防御力もアップ/gm, "raises ATK, DEF")
            .replace(/強化効果を全て解除/gm, "Removes all buff effects")
            .replace(/HPダメージを軽減 無効化する効果を無視する/gm, "Ignores effects that reduce HP damage")
            .replace(/自身の攻撃力 防御力 素早さ 最大BRV 初期BRVをアップ/gm, "raises ATK, DEF, SPD, MAX BRV, INT BRV")
            .replace(/素早さ・攻撃力・防御力もアップ/gm, "raises SPD, ATK, DEF")
            .replace(/行動後に自身のBRVを回復する/gm, "restores BRV after turn")
            .replace(/奪ったBRVを最大BRVを超えて加算する/gm, "stolen BRV may exceed MAX BRV")
            .replace(/使用時 甲羅状態なら通常状態に戻る/gm, "cancels Retreat")
            .replace(/自身の攻撃力・防御力・最大BRV・初期BRVをアップ/gm, "raises ATK, DEF, MAX BRV, INT BRV")
            .replace(/行動順を遅らせられなくなる/gm, "Cannot be delayed")
            .replace(/行動順を消失させられない/gm, "Cannot lose turn")
            .replace(/強化効果を全て解除/gm, "Cancels all buffs")
            .replace(/自身の強化効果 弱体効果を全て解除し/gm, "Cancel all buffs and debuffs on self")
            .replace(/味方全員の弱体効果を全て解除/gm, "Removes debuffs on all allies")
            .replace(/自身の強化効果を全て解除/gm, "Removes own buffs")
            .replace(/与えたBRVダメージに応じて自身のHPを回復/gm, "Recovers HP depending on BRV damage dealt")
            .replace(/自身の攻撃力・防御力・最大BRV・素早さをアップ/gm, "raises ATK, DEF, MAX BRV, SPD")
            .replace(/行動順を消失させられない/gm, "Cannot delete turns")
            .replace(/ブレイク時 ブレイク中攻撃時 行動負荷ダウン/gm, "increases turn rate when inflicting Break or attacking target afflicted with Break")
            .replace(/対象をブレイク時 行動順を1つ遅らせる/gm, "delays target 1 turn when inflicting Break")
            .replace(/初期BRV未満時 自身のBRVを加算/gm, "increases BRV when BRV less than INT BRV")
            .replace(/自身の攻撃力・素早さ・初期BRVをアップ/gm, "raises ATK, SPD, INT BRV")
            .replace(/行動順を遅らせられない/gm, "Cannot be delayed")
            .replace(/敵全体の強化効果を1個ずつ解除/gm, "Cancels buffs on all targets one by one")
            .replace(/必ずクリティカル/gm, "Guaranteed critical")
            .replace(/自身の攻撃力 初期BRV 最大BRV 素早さをアップ/gm, "raises ATK, INT BRV, MAX BRV, and SPD")
            .replace(/カウントアビリティ/gm, "Count Ability")
            .replace(/行動順を遅らせられない/gm, "Cannot be delayed")
            .replace(/必中 行動負荷が無い/gm, "instant turn rate")
            .replace(/味方全員のBRVを加算/gm, "Grants party BRV")
            .replace(/自身の攻撃力 素早さ 初期BRV 最大BRVをアップ/gm, "raises ATK, SPD, INT BRV, MAX BRV")
            .replace(/対象の強化効果を全て解除/gm, "Cancels targets buffs")
            .replace(/自身の攻撃力・素早さ・初期BRV 最大BRVをアップする/gm, "raises ATK, SPD, INT BRV, MAX BRV")
            .replace(/対象の強化効果を全て解除/gm, "Removes all target's buffs")
            .replace(/BRVダメージを軽減 無効化する効果を無視する/gm, "Ignores effects that decrease BRV damage")
            .replace(/BRV HPダメージを軽減 無効化する効果を無視する/gm, "Ignores effects that decrease BRV or HP damage")
            .replace(/受けるBRVダメージを軽減するようになる/gm, "Reduces BRV damage taken")
            .replace(/※HPダメージを受けても必ず1残る効果は無効/gm, "(ignores effects that prevent HP dropping below 1)")
            .replace(/対象の強化効果をすべて解除/gm, "Removes buffs on target")
            .replace(/行動順を遅らせられない/gm, "Cannot be delayed")
            .replace(/自身の攻撃力・防御力・初期BRV・最大BRVをアップ/gm, "raises ATK, DEF, INT BRV, MAX BRV")
            .replace(/自身の攻撃力・素早さ・初期BRV・最大BRVをアップし/gm, "raises ATK, SPD, INT BRV, MAX BRV")
            .replace(/自身の攻撃力・防御力・初期BRV・最大BRVをアップし/gm, "raises ATK, DEF, INT BRV, MAX BRV")
            .replace(/自身の攻撃力・防御力・素早さ・初期BRV・最大BRVをアップ/gm, "raises ATK, DEF, SPD, INT BRV, MAX BRV")
            .replace(/自身の攻撃力 防御力 素早さ 初期BRV 最大BRVをアップ/gm, "raises ATK, DEF, SPD, INT BRV, MAX BRV")
            .replace(/自身のBRVを初期BRVに変化させ/gm, "Increases BRV when BRV less than INT BRV")
            .replace(/キャラクターのBRV回復効果が軽減される/gm, "Reduces character's BRV recovery")
            .replace(/受けるHPダメージを(\d*)%軽減するようになる/gm, "reduces HP damage taken by $1%")
            .replace(/ブレイクで行動順を遅らせられなくなる/gm, "Cannot be delayed by breaks")
            .replace(/対象ブレイク時 ブレイク中攻撃時/gm, "When breaking or attacking broken target")
            .replace(/行動前自身のBRVを加算する/gm, "Recovers BRV at start of each turn")
            .replace(/自身のBRVが毎ACTION回復するようになる/gm, "begins recovering BRV each turn")
            .replace(/自身の攻撃力・防御力をアップ/gm, "raises ATK, DEF")
            .replace(/敵全体のHPを0にする/gm, "KO's all enemies")
            .replace(/敵全体を戦闘不能にする/gm, "Knocks out all targets")
            .replace(/対象のHPを0にする /gm, "Knocks out target")
            .replace(/対象を戦闘不能にする/gm, "Knocks out target")
            .replace(/自身の素早さ・攻撃力・防御力をアップ/gm, "raises SPD, ATK, DEF")
            .replace(/対象をブレイク/gm, "Breaks target")
            .replace(/自身のHPを回復/gm, "Recover own HP")
            .replace(/フォースタイム/gm, "force time")
            .replace(/敵全体の強化効果を(\d+)つ解除/gm, "Removes $1 buffs from each enemy")
            .replace(/【発動条件】/gm, "Trigger: ")
            .replace(/バトル開始時/gm, "Start of battle")
            .replace(/HP(\d+)%未満時/gm, "HP < $1%")

            .replace(/（銀フレーム付き弱体効果を含まない）/gm, " (silver frames excluded)")
            .replace(/（銀フレーム付強化効果は含まない）/gm, " (silver frames excluded)")
            .replace(/（銀フレーム付強化効果も含む）/gm, " (silver frames included)")
            .replace(/（銀フレーム付き強化効果を含まない）/gm, " (silver frames excluded)")
            .replace(/（銀フレーム付きは含まない）/gm, " (silver frames excluded)")
            .replace(/（銀フレーム付き強化効果は含まない）/gm, " (silver frames excluded)")
            .replace(/（銀フレーム付き含まない）/gm, " (silver frames excluded)")
            .replace(/（銀フレーム付きを含まない）/gm, " (silver frames excluded)")
            .replace(/（銀フレーム付き弱体効果を含む）/gm, " (silver frames included)")
            .replace(/（銀フレーム付きを含む）/gm, " (silver frames included)")
            .replace(/（銀フレーム付き弱体効果含む）/gm, " (silver frames included)")
            .replace(/（銀フレーム付き強化効果を含む）/gm, " (silver frames included)")
            .replace(/（銀フレーム付き弱体効果含まない）/gm, " (silver frames excluded)")
            .replace(/（ブレイクによる行動順遅延は含まない）/gm, " (delay from Break excluded)")
            .replace(/（ブレイクによる行動順遅延も含む）/gm, " (including delay from Break)")
            .replace(/（ブレイクによる行動順遅延を含む）/gm, " (including delay from Break)")
            .replace(/（ブレイクによる行動順を遅らせる効果は除く）/gm, " (delay from Break excluded)")
            .replace(/（フレーム付弱体効果は除く）/gm, " (silver frames excluded)")
            .replace(/（フレーム付き弱体効果を含む）/gm, " (silver frames included)")
            .replace(/を追加発動/gm, "triggers additional")
            .replace(/味方のBRVを加算/gm, "Increases BRV of allies")
            .replace(/自身の攻撃力と最大BRVをアップ/gm, "raises ATK, MAX BRV")
            .replace(/与えたHPダメージに応じて 自身のHP回復/gm, "recovers HP based on inflicted damage")
            .replace(/自身にBRVを加算/gm, "Increases own BRV")
            .replace(/自身にBRV加算/gm, "Increases own BRV")
            .replace(/対象に中確率で/gm, "fair chance of ")
            .replace(/攻撃力と防御力をアップ/gm, "raises ATK, DEF")
            .replace(/行動負荷ダウン/gm, "increases turn rate")
            .replace(/近距離物理/gm, "Melee")
            .replace(/遠距離物理/gm, "Ranged")
            .replace(/物理</gm, "Melee <")
            .replace(/魔法/gm, "Magic")
            .replace(/に強化効果/gm, "buff")
            .replace(/弱体効果/gm, "debuff")
            .replace(/防御力/gm, "DEF")
            .replace(/素早さ/gm, "SPD")
            .replace(/初期BRV/gm, "INT BRV")
            .replace(/最大BRV/gm, "MAX BRV")
            .replace(/さらに威力アップの/gm, "more powerful")
            .replace(/威力アップの/gm, "powerful")
            .replace(/行動負荷が低い/gm, "high turn rate")
            .replace(/必中/gm, "guaranteed hit")
            .replace(/自身のBRVを加算し/gm, "Increases BRV")
            .replace(/リキャストアビリティ/gm, "Recast ability")
            .replace(/自身のBRVを加算/gm, "Increases own BRV")
            .replace(/対象にdebuff/gm, "inflicts")
            .replace(/フォースアビリティ/gm, "force ability")
            .replace(/自身buff/gm, "Grants")
            .replace(/強化効果/gm, "Grants")
            .replace(/全体</gm, "Group <")
            .replace(/1ACTION/gm, "1 turn")
            .replace(/2ACTION/gm, "2 turns")
            .replace(/よりも/gm, "more than")
            .replace(/＜特徴＞/gm, "<Battle Aspect>")
            .replace(/味方全員/gm, "to all allies ")
            .replace(/対するカウンター/gm, "Counters against ")
            .replace(/全体 /gm, "Group ")
            .replace(/全体/gm, "Group ")
            .replace(/HIT/gm, "-hit ")
            .replace(/ダメージ固定の/gm, "Fixed damage ")
            .replace(/攻撃力/gm, "ATK")
            .replace(/次の行動時に/gm, "Uses ")
            .replace(/を使用/gm, " on next turn")
            .replace(/＋/gm, "+")
            .replace(/ : /gm, ": ")
            .replace(/敵Group にdebuff(.*)(;)/gm, "inflicts$1 on all targets")
            .replace(/(自身が受けるBRVダメージを)(.*)(％軽減するようになり)/gm, "reduces BRV damage taken by $2%")
            .replace(/(受けるBRVダメージを)(.*)(％軽減するようになる)/gm, "reduces BRV damage taken by $2%")
            .replace(/(受けるBRVダメージを)(.*)(％軽減するようになり)/gm, "reduces BRV damage taken by $2%")
            .replace(/(自身の受けるBRVダメージを)(.*)(％軽減し)/gm, "reduces BRV damage taken by $2%")
            .replace(/(受けるBRVダメージを)(.*)(％軽減する)/gm, "reduces BRV damage taken by $2%")
            .replace(/(受けるBRVダメージを)(.*)(％軽減)/gm, "reduces BRV damage taken by $2%")
            .replace(/(キャラクターの初期BRVが)(.*)(％減少される)/gm, "reduces player party's INT BRV by $2%")
            .replace(/(吹きとばし以外で受けるHPダメージを)(.*)(％軽減する)/gm, "reduces HP damage taken by $2%")
            .replace(/(受けるHPダメージを)(.*)(％軽減する)(ようになる)/gm, "reduces HP damage taken by $2%")
            .replace(/(キャラクターのBRV回復効果が)(.*)(％軽減される)/gm, "reduces player party's BRV recovery effects by $2%")
            .replace(/(HP攻撃後に保持できるBRVの上限が\s\n)(.*)(自身の所持できるBRV上限の(\d+)%までになる)/gm, "Maximum BRV that can be retained after HP Attacks is Limited to $4% of MAX BRV Cap")
            .replace(/対象buff(.*)付与/gm, "Grants$1to target")
            .replace(/敵Group へdebuff(.*)付与/gm, "inflicts$1on all targets")
            .replace(/敵Group にdebuff(.*)/gm, "inflicts$1 on all targets")
            .replace(/敵全員にdebuff(.*)/gm, "inflicts$1 on all targets")
            .replace(/味方Group buff(.*)付与/gm, "Grants$1to party")
            .replace(/ 付与/gm, "")
            .replace(/ 付与/gm, "")
            .replace(/ようになり/gm, "")
            .replace(/ようになる/gm, "")

            .replace(/・/gm, "• ")
            .replace(/　/gm, " ")

            .replace(/(\S)(<)/gm, "$1 <")
            .replace(/(>)(\S)/gm, "> $2")
            .replace(/ {2,}/gm, "\xa0\xa0\xa0")
            .replace(/(\n)(\xa0{3}[^•])/g, ";$1$2")
            .replace(/し;/gm, ";")
            .replace(/\s*;/g, ";")
            .replace(/\n• \[/gm, "\n\n[")
            .replace(/％/gm, "%")

            .replace(/(\n)(• )(\n)/gm, "$1$3")
            .replace(/(\+)(\S)/gm, "$1 $2")
            .replace(/(\+)(\S)/gm, "$1 $2")
            .replace(/\+ : /gm, "+: ")
            .replace(/）/gm, ") ")
            .replace(/（/gm, " (")
            .replace(/\+ \+/gm, "++")
            .replace(/\+\+ \+/gm, "+++")
            .replace(/\+ \)/gm, "+)")
            .replace(/k\+ /gm, "k + ")
            .replace(/し/gm, "")
            .replace(/する/gm, "")

      return (
         replacement
      )
   }
}