export default function translater_character(text, trans){
   if (text == undefined) {
      return (
         ""
      )
   } else {
      //prefilter
      const firstplace = text
         .replace(/自身に1ACTION[\s]*(「[^」]*」)付与/gm, "Grants $1 for 1 turn")
         .replace(/自身に(\d+)ACTION[\s]*(「[^」]*」)付与/gm, "Grants $2 for $1 turns")
         .replace(/パッシブ(「[^」]*」)装備時[\s]*(「[^」]*」)使用時/gm, "When using $2:")
         .replace(/パッシブ(「[^」]*」)装備時[\s]*クエスト開始時/gm, "At start of quest:")
         .replace(/クエスト開始時/gm, "At start of quest:")
         .replace(/パッシブ(「[^」]*」)装備時/gm, "At start of quest:")
         .replace(/特殊効果(「[^」]*」)に以下の効果が追加/gm, "Improves $1:")
         .replace(/(「[^」]*」)の付与されている状態で/gm, "Improves $1:")
         .replace(/自身に(「[^」]*」)が付与されている時/gm, "Improves $1:")
         .replace(/自身が(「[^」]*」)状態の時/gm, "Improves $1:")
         .replace(/・(「[^」]*」)に以下の効果追加/gm, "Improves $1:")
         .replace(/(「[^」]*」)に以下の効果が追加/gm, "Improves $1:")
         .replace(/自身に(「[^」]*」)が/gm, "Improves $1:")
         .replace(/(「[^」]*」)以上付与後/gm, "Improves $1:")
         .replace(/(「[^」]*」)の付与率/gm, "Increases change of $1")
         .replace(/(「[^」]*」)発動時/gm, "When using $1:")
         .replace(/自身に1ACTION強化効果(「[^」]*」)付与/gm, "Grants $1 for 1 turn")
         .replace(/自身に(\d+)ACTION強化効果(「[^」]*」)付与/gm, "Grants $2 for $1 turns")
         .replace(/味方全員に1ACTION(「[^」]*」)付与の効果追加/gm, "Grants Party $1 for 1 turn")
         .replace(/味方全員に(\d+)ACTION(「[^」]*」)付与の効果追加/gm, "Grants Party $2 for $1 turns")
         .replace(/使用後[\s]*(「[^」]*」)に戻る/gm, "Returns to $1 after use")
         .replace(/(「[^」]*」)中[\s]*自身のアビリティで与える/gm, "Improves $1:")
         .replace(/弱体効果が付与された敵がいる時[\s]*自身の/gm, "When enemy is debuffed:")
         .replace(/弱体効果が付与された敵がいる時/gm, "When enemy is debuffed:")
         .replace(/与えたHPダメージ依存のBRV加算量/gm, "Increases BRV by HP Damage dealt")
         .replace(/与えたBRVダメージに応じて自身の(.+)$/gm, "$1 by BRV Damage Dealt")
         .replace(/与えたHPダメージに応じて自身の(.+)[\s]*回復量の上限は最大HPの(\d+)％分/gm, "Heals HP by HP Damage dealt, up to $2% Max HP $1")
         .replace(/与えたHPダメージに応じて自身の(.+)$/gm, "$1 by HP Damage Dealt")
         .replace(/回復量の上限は 自身の最大HPの(\d+)％分/gm, "HP Heal limit $1%")
         .replace(/対象に付与されている特殊効果(「[^」]*」)の段階を1段階アップ/gm, "Inflicts 1 level of $1")
         .replace(/対象に付与されている特殊効果(「[^」]*」)の段階を(\d+)段階アップ/gm, "Inflicts $2 levels of $1")
         .replace(/(「[^」]*」)が(「[^」]*」)に変化し[\s]*以下の効果が追加/gm, "$1 becomes $2:")
         .replace(/([\s]+(「[^」]*」)+|(「[^」]*」)+)+(の)$/gm, "When using $&:")
         .replace(/((「[^」]*」)|(「[^」]*」)+|(「[^」]*」)+[\s]*(「[^」]*」)+)の[\s]*与える/gm, "When using $1:")
         .replace(/((「[^」]*」)(「[^」]*」))両方をマスターした時/gm, "When mastering both $1:")
         .replace(/(「[^」]*」)または(「[^」]*」)をマスターした時/gm, "When mastering $1 or $2:")
         .replace(/「毒」または「猛毒」の弱体効果が付与された敵がいる時/gm, "While an enemy is Poisoned:")
         .replace(/対象に1ACTION弱体効果(「[^」]*」)付与/gm, "Inflicts $1 for 1 turn")
         .replace(/対象に(\d+)ACTION弱体効果(「[^」]*」)付与/gm, "Inflicts $2 for $1 turns")
         .replace(/で[\s]*対象に[\s]*1ACTION[\s]*(「[^」]*」)付与/gm, "Inflicts $1 for 1 turn")
         .replace(/で[\s]*対象に[\s]*(\d+)ACTION[\s]*(「[^」]*」)付与/gm, "Inflicts $2 for $1 turns")
         .replace(/で[\s]*1ACTION[\s]*対象に[\s]*(「[^」]*」)を付与/gm, "Inflicts $1 for 1 turn")
         .replace(/で[\s]*(\d+)ACTION[\s]*対象に[\s]*(「[^」]*」)を付与/gm, "Inflicts $2 for $1 turns")
         .replace(/対象に[\s]*1ACTION[\s]*(「[^」]*」)付与/gm, "Inflicts $1 for 1 turn")
         .replace(/対象に[\s]*(\d+)ACTION[\s]*(「[^」]*」)付与/gm, "Inflicts $2 for $1 turns")
         .replace(/(「[^」]*」)に(「[^」]*」)の効果追加$/gm, "Improves $1: - Adds $2")
         .replace(/([^\n])(.+)依存のBRV加算量/gm, "$1Increases BRV Gains by $2")
         .replace(/敵全体に1ACTION[\s]*(「[^」]*」)付与/gm, "Inflicts $1 on all enemies for 1 turn")
         .replace(/敵全体に(\d+)ACTION[\s]*(「[^」]*」)付与/gm, "Inflicts $2 on all enemies for $1 turns")
         .replace(/与えた(.+)の(\d+)％分[\s]*自身のBRVをアップさせる/gm, "Increase BRV by $2% of HP damage dealt")

         .replace(/「物理攻撃力極小アップ」/gm, "[PHY ATK Up (Very Small)]")
         .replace(/「物理攻撃力極大アップ」/gm, "[PHY ATK Up (Very Large)]")
         .replace(/「物理攻撃力大アップ」/gm, "[PHY ATK Up (Large)]")
         .replace(/「物理攻撃力中アップ」/gm, "[PHY ATK Up (Medium)]")
         .replace(/「物理攻撃力小アップ」/gm, "[PHY ATK Up (Small)]")

         .replace(/「物理攻撃力極小ダウン」/gm, "[PHY ATK UDown (Very Small)]")
         .replace(/「物理攻撃力極大ダウン」/gm, "[PHY ATK UDown (Very Large)]")
         .replace(/「物理攻撃力大ダウン」/gm, "[PHY ATK Down (Large)]")
         .replace(/「物理攻撃力中ダウン」/gm, "[PHY ATK Down (Medium)]")
         .replace(/「物理攻撃力小ダウン」/gm, "[PHY ATK Down (Small)]")

         .replace(/「魔法攻撃力極小ダウン」/gm, "[MAG ATK Down (Very Small)]")
         .replace(/「魔法攻撃力極大ダウン」/gm, "[MAG ATK Down (Very Large)]")
         .replace(/「魔法攻撃力大ダウン」/gm, "[MAG ATK Down (Large)]")
         .replace(/「魔法攻撃力中ダウン」/gm, "[MAG ATK Down (Medium)]")
         .replace(/「魔法攻撃力小ダウン」/gm, "[MAG ATK Down (Small)]")

         .replace(/「魔法攻撃力極小アップ」/gm, "[MAG ATK Up (Very Small)]")
         .replace(/「魔法攻撃力極大アップ」/gm, "[MAG ATK Up (Very Large)]")
         .replace(/「魔法攻撃力大アップ」/gm, "[MAG ATK Up (Large)]")
         .replace(/「魔法攻撃力中アップ」/gm, "[MAG ATK Up (Medium)]")
         .replace(/「魔法攻撃力小アップ」/gm, "[MAG ATK Up (Small)]")

         .replace(/「攻撃力極小アップ」/gm, "[ATK Up (Very Small)]")
         .replace(/「攻撃力極大アップ」/gm, "[ATK Up (Very Large)]")
         .replace(/「攻撃力大アップ」/gm, "[ATK Up (Large)]")
         .replace(/「攻撃力中アップ」/gm, "[ATK Up (Medium)]")
         .replace(/「攻撃力小アップ」/gm, "[ATK Up (Small)]")

         .replace(/「攻撃力極小ダウン」/gm, "[ATK Down (Very Small)]")
         .replace(/「攻撃力極大ダウン」/gm, "[ATK Down (Very Large)]")
         .replace(/「攻撃力大ダウン」/gm, "[ATK Down (Large)]")
         .replace(/「攻撃力中ダウン」/gm, "[ATK Down (Medium)]")
         .replace(/「攻撃力小ダウン」/gm, "[ATK Down (Small)]")

         .replace(/「クリティカル率アップ」/gm, "[Critical Hit Rate Up]")

         .replace(/「クリティカル率ダウン」/gm, "[Critical Hit Rate Down]")

         .replace(/「初期BRV極小ダウン」/gm, "[INT BRV Down (Very Small)]")
         .replace(/「初期BRV極大ダウン」/gm, "[INT BRV Down (Very Large)]")
         .replace(/「初期BRV大ダウン」/gm, "[INT BRV Down (Large)]")
         .replace(/「初期BRV中ダウン」/gm, "[INT BRV Down (Medium)]")
         .replace(/「初期BRV小ダウン」/gm, "[INT BRV Down (Small)]")

         .replace(/「初期BRV極小アップ」/gm, "[INT BRV Up (Very Small)]")
         .replace(/「初期BRV極大アップ」/gm, "[INT BRV Up (Very Large)]")
         .replace(/「初期BRV大アップ」/gm, "[INT BRV Up (Large)]")
         .replace(/「初期BRV中アップ」/gm, "[INT BRV Up (Medium)]")
         .replace(/「初期BRV小アップ」/gm, "[INT BRV Up (Small)]")

         .replace(/「最大BRV極小ダウン」/gm, "[MAX BRV Down (Very Small)]")
         .replace(/「最大BRV極大ダウン」/gm, "[MAX BRV Down (Very Large)]")
         .replace(/「最大BRV大ダウン」/gm, "[MAX BRV Down(Large)]")
         .replace(/「最大BRV中ダウン」/gm, "[MAX BRV Down (Medium)]")
         .replace(/「最大BRV小ダウン」/gm, "[MAX BRV Down (Small)]")

         .replace(/「最大BRV極小アップ」/gm, "[MAX BRV Up (Very Small)]")
         .replace(/「最大BRV極大アップ」/gm, "[MAX BRV Up (Very Large)]")
         .replace(/「最大BRV大アップ」/gm, "[MAX BRV Up (Large)]")
         .replace(/「最大BRV中アップ」/gm, "[MAX BRV Up (Medium)]")
         .replace(/「最大BRV小アップ」/gm, "[MAX BRV Up (Small)]")

         .replace(/「素早さ極小アップ」/gm, "[SPD Up (Very Small)]")
         .replace(/「素早さ極大アップ」/gm, "[SPD Up (Very Large)]")
         .replace(/「素早さ大アップ」/gm, "[SPD Up (Large)]")
         .replace(/「素早さ中アップ」/gm, "[SPD Up (Medium)]")
         .replace(/「素早さ小アップ」/gm, "[SPD Up (Small)]")

         .replace(/「素早さ極小ダウン」/gm, "[SPD Down (Very Small)]")
         .replace(/「素早さ極大ダウン」/gm, "[SPD Down (Very Large)]")
         .replace(/「素早さ大ダウン」/gm, "[SPD Down (Large)]")
         .replace(/「素早さ中ダウン」/gm, "[SPD Down (Medium)]")
         .replace(/「素早さ小ダウン」/gm, "[SPD Down (Small)]")

         .replace(/「防御力極小アップ」/gm, "[DEF Up (Very Small)]")
         .replace(/「防御力極大アップ」/gm, "[DEF Up (Very Large)]")
         .replace(/「防御力大アップ」/gm, "[DEF Up (Large)]")
         .replace(/「防御力中アップ」/gm, "[DEF Up (Medium)]")
         .replace(/「防御力小アップ」/gm, "[DEF Up (Small)]")

         .replace(/「防御力極小ダウン」/gm, "[DEF Down (Very Small)]")
         .replace(/「防御力極大ダウン」/gm, "[DEF Down (Very Large)]")
         .replace(/「防御力大ダウン」/gm, "[DEF Down (Large)]")
         .replace(/「防御力中ダウン」/gm, "[DEF Down (Medium)]")
         .replace(/「防御力小ダウン」/gm, "[DEF Down (Small)]")

         .replace(/「<BRV>攻撃」/gm, "[BRV Attack]")
         .replace(/「<BRV>攻撃＋」/gm, "[BRV Attack+]")
         .replace(/「<BRV>攻撃＋＋」/gm, "[BRV Attack++]")
         .replace(/「<BRV>攻撃＋＋＋」/gm, "[BRV Attack+++]")

         .replace(/「<HP>攻撃」/gm, "[HP Attack]")
         .replace(/「<HP>攻撃＋」/gm, "[HP Attack+]")
         .replace(/「<HP>攻撃＋＋」/gm, "[HP Attack++]")
         .replace(/「<HP>攻撃＋＋＋」/gm, "[HP Attack+++]")

      const text2replace = firstplace.toString().replace(/「/gm, "|[").replace(/」/gm, "]|").split("|")
      text2replace.map((self, i) => {
         var replace = trans[self.replace(/<BRV>/gm, "BRV").replace(/<HP>/gm, "HP").replace(/\]/gm, "").replace(/\[/gm, "")]
         if (replace == undefined) {
            replace = trans[self.replace(/<BRV>/gm, "ブレイブ").replace(/\]/gm, "").replace(/\[/gm, "")]
         }
         if (replace != undefined) {
            text2replace[i] = `[${replace}]`
         }
      })
      const replaced = text2replace.join("")
      /*eslint no-irregular-whitespace: ["error", { "skipRegExps": true }]*/
      const replacement =
         replaced.toString()
            .replace(/与えるBRVダメージ上限が9999を(\d+)%分突破可能/gm, "BRV damage upper limit dealt can exceed 9999 by $1%")
            .replace(/与えるBRVダメージ上限が9999を＋(\d+)%分突破可能/gm, "BRV damage upper limit dealt can exceed 9999 by +$1%")
            .replace(/与えるHPダメージ上限が99999を＋(\d+)分突破可能/gm, "The maximum HP damage dealt can exceed 99999 by +$1%")
            .replace(/バーストモード中に使用できるFRアビリティは除く/gm, "Excludes FR Abilities that can be used during burst mode")
            .replace(/フォースタイム効果は発動しない/gm, "Force Time effect is not granted after use")
            .replace(/発動中のフォースタイム効果を受ける/gm, "Force Time effects are activated during use")
            .replace(/フォースタイムは減少しない/gm, "Force Time does not reduce")
            .replace(/HPダメージボーナス＋(\d+)%/gm, "HP Damage Bonus +$1%")
            .replace(/味方のフォースタイム中/gm, "During an ally's Force Time")
            .replace(/自身の属性弱点攻撃BRV威力小アップ/gm, "BRV damage boost when attacking elemental weakness")
            .replace(/味方全員の受けるHPダメージ軽減/gm, "Reduces party's HP damage taken")
            .replace(/最後の<HP>攻撃後の/gm, "after the last <HP> Attack")
            .replace(/与えた合計HPダメージの(\d+)%分自身のBRVをアップさせる/gm, "Increases BRV $1% of HP damage dealt")
            .replace(/行動負荷がない/gm, "Instant turn rate")
            .replace(/自身に付与されている強化効果を(\d+)ACTION延長/gm, "Extends own active buff duration $1 turns")
            .replace(/加算したBRVを最大BRVを超えて加算する(\s*)上限はそれぞれの最大BRVの(\d+)%分/gm, "Allows for $2% Gained MAX BRV Overflow")
            .replace(/自身の付与する強化効果の付与期間を(\d+)ACTION追加/gm, "extends duration of granted buffs by $1 turns")
            .replace(/自身が与えたBRVダメージよりも多くのBRVを得る/gm, "Greater BRV gained than BRV damage dealt")
            .replace(/([^・\s]+)に依存したBRV加算量/gm, "Increases BRV by $1 ")
            .replace(/([^・\s]+)に依存したBRV加算量/gm, "Increases BRV by $1 ")
            .replace(/(\[[^\]]*\])使用回数＋(\d+)/gm, "$1 uses +$2")
            .replace(/(\[.+\])使用後/gm, "When using $1:")
            .replace(/(\[.+\])(使用時)/gm, "When using $1:")
            .replace(/所持できるBRV上限に依存した量のHPダメージを与える/gm, "deal HP damage based on held bravery limit")
            .replace(/総ACTION数に加算されない[\s]*バーストモード中 召喚中およびフレンドサポートの残りACTIONは消費される/gm, "do not add to turn count; do consume turns during burst mode, summoning, support")
            .replace(/自身の付与する弱体効果の付与期間を(\d+)ACTION追加/gm, "Extends granted debuffs turns by $1")
            .replace(/自身の最初の行動時[\s]*アビリティの使用回数を消費しない/gm, "Next turn does not consume ability use on first turn")
            .replace(/使用後[\s]*次の行動時[\s]*アビリティの使用回数を消費しない/gm, "Next turn does not consume ability use")
            .replace(/一部のアビリティを除く/gm, "except for some abilities")
            .replace(/(\[[^\]]*\])が付与されている味方全員の/gm, "Improves $1:")
            .replace(/(\[.+\])(付与中)/gm, "Improves $1:")
            .replace(/味方全員の(.+)(\d+)％アップ/gm, "Adds Party $1 Up by $2%")
            .replace(/(\[[^\]]*\])の付与する弱体効果の/gm, "Improves $1:")
            .replace(/さらにBRVを(\d+)\.0倍/gm, "Increases BRV by x$1")
            .replace(/自身の与えるHPダメージ/gm, "Adds HP Damage ")
            .replace(/与えた合計HPダメージの(\d+)％分自身のBRVをアップ/gm, "Increases BRV by $1% of HP Damage Dealt")
            .replace(/BRVダメージを(\d+)％アップ/gm, "Adds BRV Damage Up by $1%")
            .replace(/(\[[^\]]*\])(\d+)段階付与中/gm, "While $1 is at level $2")
            .replace(/弱点をついた時 与えるBRVダメージ/gm, "Increases BRV damage to debuffed targets ")
            .replace(/同名の強化効果は重複しない/gm, "Buffs of the same name do not stack")
            .replace(/※同一パッシブの効果は重複しない/gm, "*Effects from the same passive do not overlap")
            .replace(/追撃時に与えるHPダメージ(\d+)％アップ/gm, "Increases HP Damage by $1% during knock backs")
            .replace(/付与する強化効果の期間を1ACTION延長/gm, "Extends granted buff durations by 1 turn")
            .replace(/付与する強化効果の期間を(\d+)ACTION延長/gm, "Extends granted buff durations by $1 turns")
            .replace(/自身に付与されている(\[[^\]]*\])の段階を[\s]*1段階アップ/gm, "Grants 1 level of $1")
            .replace(/自身に付与されている(\[[^\]]*\])の段階を[\s]*(\d+)段階アップ/gm, "Grants $2 levels of $1")
            .replace(/味方全員に(\[[^\]]*\])付与の/gm, "Grants Party $1")
            .replace(/弱体効果の期間を1ACTION延長/gm, "Extends inflicted debuffs by 1 turn")
            .replace(/弱体効果の期間を(\d+)ACTION延長/gm, "Extends inflicted debuffs by $1 turns")
            .replace(/自身に((\[[^\]]*\])+)付与の[\s]*1ACTION期間追加/gm, "Grants $1 for 1 turn")
            .replace(/自身に((\[[^\]]*\])+)付与の[\s]*(\d+)ACTION期間追加/gm, "Grants $1 for $3 turns")
            .replace(/対象のHPが最大HPの(\d+)％以下の時/gm, "When the target has less than $1% HP")
            .replace(/自身以外の味方全員に1ACTION[\s]*(\[[^\]]*\])付与/gm, "Grants Party (except self) $1 for 1 turn")
            .replace(/自身以外の味方全員に(\d+)ACTION[\s]*(\[[^\]]*\])付与/gm, "Grants Party (except self) $2 for $1 turns")
            .replace(/<HP>攻撃後[\s]*与えたHPダメージに依存した量のBRVを/gm, "Increases BRV by HP Damage dealt ")
            .replace(/・HIT時[\s]*次回行動順が[\s]*ターゲットの直前に移動（召喚中は除く）/gm, "\xa0┬ If next turn is after the target,\n\xa0└─ Moves next turn to just before the target (excludes Summon Phase)")
            .replace(/\[与えるBRVダメージ上限が9999を(\d+)％分突破可能[\s]*（(\d+)まで）\]/gm, "Adds BRV Damage Cap Up by $1% ($2)")
            .replace(/自身以外の味方へのBRV加算量小アップ/gm, "Increases BRV gains to Party (except self)")
            .replace(/自身のBRVを乗算する前に自身に/gm, "Increases own BRV by current BRV")
            .replace(/BRV乗算量小アップ/gm, "Increases BRV gains by current BRV")
            .replace(/弱体効果が付与された対象に[\s]*より大きなBRVダメージ/gm, "Increases BRV damage to debuffed targets ")
            .replace(/(\[[^\]]*\])付与を味方全体化し/gm, "Grants Party $1")
            .replace(/<BRV>攻撃前に味方全員に/gm, "To party before <BRV> Attack")
            .replace(/([^・]+)に依存したBRV加算の加算量が/gm, "Increases BRV by $1 ")
            .replace(/自身の(.+)に依存した量のBRVを加算/gm, "Increases BRV by $1 ")
            .replace(/自身のBRVを乗算する前に/gm, "Before BRV increase by current BRV")
            .replace(/自身の(.+)に依存した量のBRVを自身に加算/g, "Increase BRV by $1")
            .replace(/最終HIT後 自身のBRVが最大BRVの(\d+)％以上時/gm, "If BRV is at least $1% of MAX BRV after final hit")
            .replace(/対象以外に与えるHPダメージ/gm, "Increases Splash <HP> damage to non-targets ")
            .replace(/自身の(.+)に依存した量のBRVを味方全員に加算/gm, "Increases Party BRV by $1")
            .replace(/自身のBRVが最大BRVの(\d+)％以上の時/gm, "While BRV is at least $1% of MAX BRV:")
            .replace(/最大HPを超えてHPが回復した時/gm, "When HP is recovered:")
            .replace(/自身の(.+)に依存したBRV加算/gm, "Increases BRV by $1")
            .replace(/付与対象が全体化/gm, "Target changed to <AOE> ")
            .replace(/期間も1ACTION延長/gm, " extended by 1 turn ")
            .replace(/期間も(\d+)ACTION延長/gm, " extended by $1 turns ")
            .replace(/強化効果を奪う確率/gm, "Increases chances of stealing buff ")
            .replace(/<BRV>攻撃のHIT数が(\d+)HITになり/gm, "Increases <BRV> hits to $1")
            .replace(/2HIT目の攻撃対象を全体化/gm, "2nd <BRV> hit becomes <AOE>")
            .replace(/1HIT目のBRV威力を/gm, "Increases BRV Power of 1st <BRV> hit")
            .replace(/自身に自身の(.+)に依存した量のBRV加算/gm, "Increases BRV by $1")
            .replace(/<BRV>攻撃の攻撃対象全体化/gm, "Becomes <AOE> <BRV> Attack")
            .replace(/自身のBRVが最大BRVの[\s]*(\d+)％以上の時[\s]*追加<HP>攻撃が発動/gm, "Triggers <HP> attack if BRV is $1% of MAX BRV")
            .replace(/味方全員に自身の(.+)に[\s]*依存した量のBRV加算/gm, "Increases Party BRV by $1")
            .replace(/追撃(\[[^\]]*\])に影響なし/gm, "Does not effect knock back $1")
            .replace(/攻撃対象が単体時[\s]*与えるBRVダメージ中アップ/gm, "Increases BRV damage to single targets by 60%")
            .replace(/攻撃対象単体時[\s]*与えるBRVダメージ中アップ/gm, "Increases BRV damage to a single target by 60%")
            .replace(/ターゲット以外の吹きとばしやすさは[\s]*ブレイク状況の影響なし/gm, "Knocking Back non-targets is not effected by break")
            .replace(/弱体効果が付与された敵攻撃時[\s]*威力がさらに/gm, "Increases BRV damage to debuffed targets ")
            .replace(/超えたHP分[\s]*自身以外の味方のHPを分配回復/gm, "Excess HP recovery is split between Party (except self) ")
            .replace(/与えたHPダメージに応じたHP回復/gm, "Heals HP by HP Damage Dealt ")
            .replace(/対象以外にも(\d+)％分のHPダメージ/gm, "Deals $1%  Splash <HP> damage to non-targets")
            .replace(/味方全員に1ACTION(\[[^\]]*\])付与/gm, "Grants Party $1 for 1 turn")
            .replace(/味方全員に(\d+)ACTION(\[[^\]]*\])付与/gm, "Grants Party $2 for $1 turns")
            .replace(/付与する強化効果の1ACTION期間延長/gm, "Extends granted buffs by 1 turn")
            .replace(/付与する強化効果の(\d+)ACTION期間延長/gm, "Extends granted buffs by $1 turns")
            .replace(/自身に自身の(.+)に依存した量のBRVを加算/gm, "Increases BRV by $1")
            .replace(/最大HPに依存したHP回復量/gm, "Heals HP by Max HP ")
            .replace(/攻撃力に依存したBRV加算量/gm, "Increases BRV by ATK ")
            .replace(/与えたHPダメージに応じたHP回復量/gm, "Heals HP by HP Damage Dealt ")
            .replace(/自身に1ACTION(\[[^\]]*\])1段階付与/gm, "Grants 1 level of $1 for 1 turn")
            .replace(/自身に1ACTION(\[[^\]]*\])(\d+)段階付与/gm, "Grants $2 levels of $1 for 1 turn")
            .replace(/自身に(\d+)ACTION(\[[^\]]*\])1段階付与/gm, "Grants 1 level of $2 for $1 turns")
            .replace(/自身に(\d+)ACTION(\[[^\]]*\])(\d+)段階付与/gm, "Grants $3 levels of $2 for $1 turns")
            .replace(/最後の<HP>攻撃を除く[\s]*<HP>攻撃後/gm, "After each HP Attack, except last")
            .replace(/追撃時 与えるBRV・HPダメージがアップ/gm, "BRV and HP Damage Up during a Knock Back")
            .replace(/自身のHPが最大HPの50％以上の時[\s]*敵の攻撃でHPダメージを受けても[\s]*必ず1残る/gm, "Prevents KO if HP is at least 50% of Max HP and leaves HP value at 1")
            .replace(/超えたHP分 自身のBRVをアップ[\s]*BRVアップの上限は 自身の初期BRV(\d)+％分/gm, "Converts excess HP recovered to BRV, up to $1% INT BRV")
            .replace(/超えたHP分 自身のBRVをアップ[\s]*BRVアップの上限は 自身の初期BRV(\d)+%分/gm, "Converts excess HP recovered to BRV, up to $1% INT BRV")
            .replace(/与えたHPダメージに依存した量のBRVを[\s]+自身以外の味方全員に加算/gm, "Increase Party (except self) BRV by HP damage dealt")
            .replace(/攻撃対象が単体の時 与えるBRVダメージ中アップ/gm, "Increases BRV damage to single targets by 60%")
            .replace(/(奪ったBRVを最大BRVを超えて加算する[\s]+上限は自身の最大BRVの(\d+)％分)/gm, "Allows for $2% Stolen MAX BRV Overflow")
            .replace(/(奪ったBRVを最大BRVを超えて加算する[\s]+上限は自身の最大BRVの(\d+)%分)/gm, "Allows for $2% Stolen MAX BRV Overflow")
            .replace(/攻撃対象が単体の時[\s]*与えるBRVダメージ(\d+)％アップ/gm, "Increases BRV damage by $1% whe attacking single targets")
            .replace(/さらに1ACTION期間延長/gm, "Extends duration by 1 turn")
            .replace(/さらに(\d+)ACTION期間延長/gm, "Extends duration by $1 turns")
            .replace(/自身のHPが最大HPの(\d+)％以上の時/gm, "When HP is at least $1% Max HP:")
            .replace(/<BRV>攻撃前に自身に/gm, "Before BRV Attack")
            .replace(/弱体効果付与成功後/gm, "When inflicting a debuff:")
            .replace(/HP回復上限が/gm, "Increases HP Heals ")
            .replace(/以下が追加発動/gm, " additional effects ")
            .replace(/ターゲットのブレイク状態を解除/gm, "Resets Target's Break")
            .replace(/ターゲットを吹きとばす/gm, "Initiates a <Knock Back> on target")
            .replace(/吹きとばない/gm, "Cannot knock back")
            .replace(/対象に付与されている強化効果を[\s]*全て＋1ACTION/gm, "Extends buffs granted to target by 1 turn")
            .replace(/対象に付与されている強化効果を[\s]*全て＋(\d+)ACTION/gm, "Extends buffs granted to target by $1 turns")
            .replace(/初期BRVに依存したBRV加算量/gm, "Increases BRV by INT BRV ")
            .replace(/自身に自身の初期BRVに依存した量のBRVを加算/gm, "Increases BRV by INT BRV")
            .replace(/自身の初期BRVに依存した量のBRVを加算/gm, "Increases BRV by INT BRV")
            .replace(/自身を狙っている敵を攻撃した時/gm, "When attacking enemy targeting self:")
            .replace(/自身を狙っていないターゲットを/gm, "When attacking enemy not targeting self:")
            .replace(/初期BRV未満の味方がいる時/gm, "When an ally's BRV is below their INT BRV")
            .replace(/自身のアビリティの使用回数が残り1回の時に/gm, "When there is only 1 ability use left:")
            .replace(/カードストックが3の時/gm, "While [Cards] is at level 3:")
            .replace(/自身のHPが最大HPの(\d+)％未満の時/gm, "When HP is under $1%:")
            .replace(/<BRV>攻撃を受けた時/gm, "When receiving a BRV attack:")
            .replace(/追加<HP>攻撃が発動/gm, "Triggers <HP> Attack")
            .replace(/自身に付与されている強化効果を全て＋1ACTION/gm, "Extends duration of own existing buffs by 1 turn")
            .replace(/自身に付与されている強化効果を全て＋(\d+)ACTION/gm, "Extends duration of own existing buffs by $1 turns")
            .replace(/自身のBRVが初期値未満の時/gm, "When BRV is below INT BRV:")
            .replace(/自身の攻撃力に依存した自身へのBRV加算量中アップ/gm, "Increases BRV by ATK")
            .replace(/自身の攻撃力に依存した量のBRVを加算/gm, "Increases BRV by ATK")
            .replace(/クリティカルヒット時 与えるBRVダメージ/gm, "Increases critical BRV damage")
            .replace(/超えたHPの(\d+)％分 味方全員のHPに分配/gm, "If the HP recovery amount exceeds $1% of Max HP, ")
            .replace(/回復量の上限は 対象の最大HPの(\d+)％分/gm, "*HP recovered is limited to $1% of each target's Max HP")
            .replace(/全体攻撃使用時[\s]*対象が1人ならば/gm, "When dealing a Group BRV Attack to a single target:")
            .replace(/全体攻撃使用時/gm, "When dealing Group Attacks:")
            .replace(/与えるBRVダメージが1.(\d)+倍/gm, "Increases BRV Damage by $10%")
            .replace(/自身のHPが回復した時/gm, "When own HP is Healed:")
            .replace(/強化効果を付与した時/gm, "When granting a buff:")
            .replace(/味方全員のすでに付与されている強化効果を[\s]*全て＋1ACTION（1回のみ）/gm, "Extends existing Party buffs by 1 turn")
            .replace(/味方全員のすでに付与されている強化効果を[\s]*全て＋(\d+)ACTION（1回のみ）/gm, "Extends existing Party buffs by $1 turn2")
            .replace(/自身に強化効果が2つ以上付与されている時/gm, "While at least 2 buffs are active:")
            .replace(/自身に強化効果が付与されている時/gm, "While buffed:")
            .replace(/自身のHPが最大HPの50％未満の時/gm, "When HP is below 50%:")
            .replace(/複数アビリティをマスターしても効果は重複しない/gm, "*Mastering multiple abilities does not duplicate effects")
            .replace(/アビリティ連続使用時/gm, "When using abilities continuously:")
            .replace(/敵の攻撃を回避した時/gm, "When evading an attack:")
            .replace(/自身に弱体効果が付与される確率を/gm, "Adds Debuff Evasion Rate Up")
            .replace(/味方全員に入るブレイクボーナスを/gm, "Party BRV Break Bonus Up")
            .replace(/味方が敵をブレイクした時/gm, "When an ally inflicts a BRV Break:")
            .replace(/自身が敵をブレイクした時/gm, "When inflicting a BRV Break:")
            .replace(/敵をブレイクした時 自身に入る/gm, "When inflicting a BRV Break:")
            .replace(/味方が敵を戦闘不能にした時/gm, "When an ally defeats an enemy:")
            .replace(/敵を戦闘不能にした時/gm, "When defeating an enemy:")
            .replace(/パーティの女性キャラクター数に応じて/gm, "For every female in Party:")
            .replace(/自身がクリティカルヒットで与える/gm, "When dealing Critical BRV Damage:")
            .replace(/クリティカルヒット発生時/gm, "When dealing a critical hit:")
            .replace(/クリティカルヒットでBRVダメージを/gm, "When dealing a critical hit:")
            .replace(/(<[^>]*>)属性攻撃でダメージを与えた時/gm, "When dealing $1 BRV damage:")
            .replace(/敵をブレイクした時[\s]+1ACTION/gm, "For 1 turn after breaking enemy")
            .replace(/敵をブレイクした時[\s]+(\d+)ACTION/gm, "For $1 turns after breaking enemy")
            .replace(/使用後[\s]+1ACTION/gm, " for 1 turn after")
            .replace(/使用後[\s]+(\d+)ACTION/gm, " for $1 turns after")
            .replace(/ブレイクされずに1残る/gm, "Break is avoided and BRV drops to 1")
            .replace(/HPダメージを受けた時/gm, "When taking HP damage:")
            .replace(/最終バトル開始時にHPがMAXの時/gm, "If HP is MAX at start of last wave:")
            .replace(/自身のBRVが最大BRVの50％以上の時/gm, "When BRV is at least 50% MAX BRV:")
            .replace(/各バトル先頭行動時/gm, "At start of wave:")
            .replace(/バトル開始時/gm, "At start of wave:")
            .replace(/自身のBRVが0以下になった時/gm, "When BRV equals 0:")
            .replace(/自身のBRVが0になった時/gm, "When BRV equals 0:")
            .replace(/敵を吹きとばした時/gm, "During a Knock Back:")
            .replace(/弱体効果発生率がダウン/gm, "Debuff Evasion Rate Up")
            .replace(/自身に入るブレイクボーナスを小アップ/gm, "Adds Break Bonus Up")
            .replace(/※通常\[BRV Attack\]が変化した[\s]*アビリティ使用後も含む/gm, "*When using BRV Attack or abilities changed from BRV Attack")
            .replace(/※通常\[BRV Attack\]通常\[HP Attack\]が変化した[\s]+アビリティ使用時も含む/gm, "*Also applies to abilities changed from BRV Attack, HP Attack")
            .replace(/※通常\[BRV Attack\]通常\[HP Attack\]が変化した[\s]+アビリティも含む/gm, "*Also applies to abilities changed from BRV Attack, HP Attack")
            .replace(/攻撃力が最大10回まで極小アップ/gm, "Adds ATK Up by 2% up to 10 times (max 20%)")
            .replace(/通常\[BRV Attack\]およびアビリティを使用する度に/gm, "When using BRV Attack or abilities changed from BRV Attack")
            .replace(/ウルフ種に/gm, "against wolf types")
            .replace(/人型種に/gm, "against Humanoid types")
            .replace(/スケルトン種に/gm, "against skeleton types")
            .replace(/ゴースト種の/gm, "against ghost types")
            .replace(/機械種に/gm, "against machine types ")
            .replace(/※通常(\[[^\]]*\])が変化した[\s]+アビリティも含む/gm, "*Also applies to abilities changed from HP Attack")
            .replace(/※通常\[HP Attack\]が変化した[\s]+アビリティ使用時も含む/gm, "*Also applies to abilities changed from HP Attack")
            .replace(/※通常\[BRV Attack\]が変化した[\s]+アビリティ使用時も含む/gm, "*Also applies to abilities changed from BRV Attack")
            .replace(/※通常\[BRV Attack\]が変化した[\s]+アビリティも含む/gm, "*Also applies to abilities changed from BRV Attack")
            .replace(/自身のBRVが初期値以上で[\s]+対象のBRVが自身の2倍以上の時/gm, "While BRV is ≥ INT BRV and target's BRV is x2 curent BRV")
            .replace(/ターゲット以外にも(\d+)％分のHPダメージ/gm, "Deals $1% Splash <HP> damage to non-targets")
            .replace(/自身が付与する強化効果の(\d+)ACTION期間延長/gm, "Granted buff duration +$1")
            .replace(/自身の(.+)に依存したBRV加算量/gm, "Increases BRV by $1")
            .replace(/自身の(.+)に依存したHP回復量/gm, "Increases HP Heals by ")
            .replace(/攻撃前に自身に自身の(.+)に[\s]+依存した量のBRVを加算/gm, "Increases BRV by $1")
            .replace(/攻撃前 味方全員に自身の(.+)に依存した量のBRVを加算/gm, "Increase Party BRV by $1")
            .replace(/味方全員に自身の(.+)に依存した量のBRVを加算/gm, "Increase Party BRV by $1")
            .replace(/段階によって効果は上昇しない/gm, "Effects don't increase based on level")
            .replace(/HPダメージは減少しない/gm, "does not reduce HP damage")
            .replace(/自身の<HP>攻撃時に消費するBRVが減少する/gm, "Reduces BRV consumed by <HP> attacks")
            .replace(/(\[[^\]]*\])の効果を1ACTION期間延長/gm, "Extends $1 by 1 turn")
            .replace(/(\[[^\]]*\])の効果を(\d+)ACTION期間延長/gm, "Extends $1 by $2 turns")
            .replace(/自身の付与する弱体効果の1ACTION期間延長/gm, "Extends duration of inflicted debuffs by 1 turn")
            .replace(/自身の付与する弱体効果の(\d+)ACTION期間延長/gm, "Extends duration of inflicted debuffs by $1 turns")
            .replace(/与えたHPダメージに依存した量のBRVを味方全員に加算/gm, "Increase Party BRV by HP damage dealt")
            .replace(/与えたBRVダメージに依存した量のBRVを味方全員に加算/gm, "Increase Party BRV by BRV damage dealt")
            .replace(/使用後 ターゲットに追加[\s]+/gm, "Triggers ")
            .replace(/通常(\[[^\]]*\])が以下の(\[[^\]]*\])に変化/gm, "Grants $2:")
            .replace(/自身が攻撃回避時に発動する攻撃の/gm, "On Attack triggered from Evading")
            .replace(/奪ったBRVを最大BRVを超えて加算する上限#e(\d+)d％アップ/gm, "\xa0- Increases Stolen MAX BRV Overflow by ")
            .replace(/奪ったBRVを最大BRVを超えて加算する上限(\d+)％アップ/gm, "\xa0- Increases Stolen MAX BRV Overflow by $1%")
            .replace(/弱点をついた時 与えるBRVダメージ(\d+)％アップ/gm, "\xa0- Increases Weakness BRV damage by $1%")
            .replace(/与えるBRVダメージ#e(\d+)d％アップ/gm, "\xa0- Increases BRV damage by ")
            .replace(/与えるBRVダメージ(\d+)％アップ/gm, "\xa0- Increases BRV damage by $1%")
            .replace(/自身の(.*)に依存したBRV加算を味方全体化し/gm, "Extends BRV Gains by $1 to Party")
            .replace(/最後の<HP>攻撃を除く<HP>攻撃HIT時も[\s]+ターゲット以外にもターゲットに与えた合計HPダメージの(\d+)％分のHPダメージ/gm, "Deals $1% Splash <HP> Damage after each HP Attack, execpt last")
            .replace(/<BRV>攻撃のHIT数が(\d+)HITに変化し/gm, "Increases <BRV> hits to $1")
            .replace(/(自身に1ACTION(\[[^\]]*\])付与)/gm, "Grants $2 for 1 turn")
            .replace(/(自身に(\d+)ACTION(\[[^\]]*\])付与)/gm, "Grants $3 for $2 turns")
            .replace(/(\[[^\]]*\])の1ACTION期間延長/gm, "Extends $1 for 1 turn")
            .replace(/(\[[^\]]*\])の(\d+)ACTION期間延長/gm, "Extends $1 for $2 turns")
            .replace(/・(\[[^\]]*\])のリキャストスピード小アップ/gm, "\nWhen using $1:\n\xa0- Increases Recast Speed by 20%")
            .replace(/最初の<HP>攻撃後[\s]+与えた合計HPダメージの(\d+)％分自身のBRVをアップさせる/gm, "Increases BRV by $1% of HP damage dealt after first HP Attack")
            .replace(/最後の<HP>攻撃後[\s]+与えた合計HPダメージに依存した量のBRVを味方全員に加算/gm, "Increases Party BRV by total HP damage dealt after last HP Attack")
            .replace(/最後の<HP>攻撃HIT時[\s]+ターゲット以外にも与えた合計HPダメージの(\d+)％分のHPダメージ/gm, "Deals $1% Splash <HP> damage to non-targets on last HP Attack")
            .replace(/ターゲット以外にも与えた合計HPダメージの(\d+)％分のHPダメージ/gm, "Deals $1% Splash <HP> damage to non targets")
            .replace(/自身の与えるBRVダメージ上限が9999を(\d+)％分突破可能（(\d+)まで）/gm, "Adds BRV Damage Cap Up by $1% ($2)")
            .replace(/行動負荷軽減効果/gm, "Increases turn rate")
            .replace(/行動負荷が高い/gm, "low turn rate")
            .replace(/の使用回数/gm, " uses ")
            .replace(/対象への効果を味方全体化/gm, "Buffs granted extend to party")
            .replace(/味方全体化/gm, " extended to party")
            .replace(/(\[[^\]]*\])の行動負荷を[\s]*極小ダウン/gm, "When using $1:\n\xa0- Increases Turn Rate (Very Small)")
            .replace(/(\[[^\]]*\])の行動負荷を[\s]*極大ダウン/gm, "When using $1:\n\xa0- Increases Turn Rate (Very Large)")
            .replace(/(\[[^\]]*\])の行動負荷を[\s]*小ダウン/gm, "When using $1:\n\xa0- Increases Turn Rate (Small)")
            .replace(/(\[[^\]]*\])の行動負荷を[\s]*中ダウン/gm, "When using $1:\n\xa0- Increases Turn Rate (Medium)")
            .replace(/(\[[^\]]*\])の行動負荷を[\s]*大ダウン/gm, "When using $1:\n\xa0- Increases Turn Rate (Large)")
            .replace(/BRV加算量も極小アップ/gm, "Increases BRV Gains (Very Small)")
            .replace(/BRV加算量も小アップ/gm, "Increases BRV Gains (Small)")
            .replace(/BRV加算量も中アップ/gm, "Increases BRV Gains (Medium)")
            .replace(/BRV加算量も大アップ/gm, "Increases BRV Gains (Large)")
            .replace(/BRV加算量も極大アップ/gm, "Increases BRV Gains (Very Large)")
            .replace(/合計BRV威力も極小アップ/gm, "Increases BRV potency (Very Small)")
            .replace(/合計BRV威力も小アップ/gm, "Increases BRV potency (Small)")
            .replace(/合計BRV威力も中アップ/gm, "Increases BRV potency (Medium)")
            .replace(/合計BRV威力も大アップ/gm, "Increases BRV potency (Large)")
            .replace(/合計BRV威力も極大アップ/gm, "Increases BRV potency (Very Large)")
            .replace(/BRV威力極小アップ/gm, "Increases BRV potency (Very Small)")
            .replace(/BRV威力小アップ/gm, "Increases BRV potency (Small)")
            .replace(/BRV威力中アップ/gm, "Increases BRV potency (Medium)")
            .replace(/BRV威力大アップ/gm, "Increases BRV potency (Large)")
            .replace(/BRV威力極大アップ/gm, "Increases BRV potency (Very Large)")
            .replace(/威力極大アップ/gm, " Power Up (Large)")
            .replace(/威力極小アップ/gm, " Power Up (Small)")
            .replace(/威力小アップ/gm, " Power Up (Small)")
            .replace(/威力中アップ/gm, " Power Up (Medium)")
            .replace(/威力大アップ/gm, " Power Up (Large)")
            .replace(/は威力がアップし/gm, "Increases Power ")
            .replace(/HP回復量極小アップ/gm, "Increases HP Heals (Very Small)")
            .replace(/HP回復量小アップ/gm, "Increases HP Heals (Small)")
            .replace(/HP回復量中アップ/gm, "Increases HP Heals (Medium)")
            .replace(/HP回復量大アップ/gm, "Increases HP Heals (Large)")
            .replace(/HP回復量極大アップ/gm, "Increases HP Heals (Very Large)")
            .replace(/HP極小回復/gm, "HP Heals (Very Small)")
            .replace(/HP極大回復/gm, "HP Heals (Very Large)")
            .replace(/HP小回復/gm, "HP Heals (Small)")
            .replace(/HP中回復/gm, "HP Heals (Medium)")
            .replace(/HP大回復/gm, "HP Heals (Large)")
            .replace(/HP回復/gm, "HP Heals")
            .replace(/([^・]+)に依存した量のBRV加算量/gm, "Increases BRV by $1 ")
            .replace(/最後の<HP>攻撃HIT時/gm, "on last HP attack")
            .replace(/対象の行動順を1つ遅らせる/gm, "delays target 1 turn")
            .replace(/対象の行動順を(\d+)つ遅らせる/gm, "Delays target $1 turns")
            .replace(/与えたHPダメージに応じて自身のHP回復/gm, "Recovers own HP depending on HP damage dealt")
            .replace(/行動後に自身のBRVを加算する/gm, "Increases BRV after turn")
            .replace(/与えるHPダメージは等倍/gm, "deals full <HP> damage to each target")
            .replace(/与えるHPダメージは分配/gm, "Deals split <HP> damage to each target")
            .replace(/自身の初期BRVに応じて 自身のBRVを加算後/gm, "Increases BRV based on own INT BRV")
            .replace(/対象をブレイク時 行動順を1つ遅らせる/gm, "delays target 1 turn when inflicting Break")
            .replace(/対象をブレイク時 行動順を(\d+)つ遅らせる/gm, "delays target $1 turns when inflicting Break")
            .replace(/自身の弱体効果を全て解除し（銀フレーム付き含まない）/gm, "Removes own debuffs (not including silver frames)")
            .replace(/対象をブレイク時 ブレイク中攻撃時 行動負荷ダウン/gm, "higher turn rate when inflicting Break or attacking target afflicted with Break")
            .replace(/強化効果を全て解除（銀フレーム付き強化効果は含まない）/gm, "Removes all buff effects (excluding buffs  with silver frame)")
            .replace(/所持BRV上限が(\d+)を突破/gm, "Maximum BRV obtained exceed $1")
            .replace(/自身の弱体効果を全て解除（フレーム付き弱体効果を含む）/gm, "removes own debuffs (silver frames included)")
            .replace(/自身の弱体効果を全て解除し（銀フレーム付きを含む）/gm, "Removes own debuffs (including silver frames)")
            .replace(/自身の弱体効果を全て解除し（銀フレーム付き弱体効果含まない）/gm, "Removes own debuffs (frames excluded)")
            .replace(/自身の弱体効果を全て解除し（銀フレーム付き弱体効果含む）/gm, "Removes own debuffs (including debuffs with silver frames)")
            .replace(/自身の弱体効果を全て解除（銀フレーム付き弱体効果含む）/gm, "Removes all own debuffs (including debuffs with silver frames)")
            .replace(/行動順を消失させられない/gm, "Cannot lose turn")
            .replace(/自身の弱体効果を全て解除（銀フレーム付き弱体効果を含まない）/gm, "Removes own debuffs (not including debuffs with silver frames)")
            .replace(/敵全体の強化効果を全て解除し（銀フレーム付き強化効果を含まない）/gm, "Cancels all target's buffs (not including buffs with silver frame)")
            .replace(/強化効果を全て解除（銀フレーム付強化効果も含む）/gm, "Cancels all buffs (including buffs with silver frames)")
            .replace(/対象の強化効果を全て解除（銀フレーム付き強化効果を含まない）/gm, "Cancels target's buffs (not including buffs with silver frames)")
            .replace(/自身の強化効果 弱体効果を全て解除し（銀フレーム付きを含む）/gm, "Cancel all buffs and debuffs on self (including with silver frames)")
            .replace(/自身の弱体効果を全て解除し（銀フレーム付き弱体効果を含む）/gm, "Cancels own debuffs (including debuffs with silver frames)")
            .replace(/味方全員の弱体効果を全て解除（銀フレーム付きを含む）/gm, "Removes debuffs on all allies (including with silver frames)")
            .replace(/敵全体の強化効果 自身の弱体効果を全て解除（銀フレーム付き弱体効果を含む）/gm, "Cancels buffs on all targets and removes own debuffs(including debuffs with silver frames)")
            .replace(/対象の強化効果を全て解除し（銀フレーム付き強化効果を含む）/gm, "Removes targets buffs (including buffs with silver frames)")
            .replace(/対象の強化効果を全て解除（銀フレーム付強化効果は含まない）/gm, "Removes all targets buffs (excluding buffs with silver frames)")
            .replace(/敵全体の強化効果を全て解除し（銀フレーム付き強化効果を含む）/gm, "Cancels all targets buffs (including buffs with silver frames)")
            .replace(/自身の弱体効果 敵全体の強化効果を全て解除（銀フレーム付きを含む）/gm, "Removes own debuffs and cancels buffs on all targets (including with silver frames)")
            .replace(/自身の強化効果を全て解除（銀フレーム付きを含まない）/gm, "Removes own buffs (not including with silver frames)")
            .replace(/対象の強化効果 自身の弱体効果を全て解除（銀フレーム付きを含む）/gm, "Cancels targets buffs; removes own debuffs (including with silver frames)")
            .replace(/自身の弱体効果を全て解除（銀フレーム付きを含まない）/gm, "Removes own debuffs (not including silver frames)")
            .replace(/敵全体の強化効果を全て解除（銀フレーム付き強化効果を含む）/gm, "Cancels buffs on all targets (including with silver frames)")
            .replace(/対象の強化効果を全て解除（銀フレーム付き強化効果は含まない）/gm, "Cancels buffs on all targets (excluding silver frames)")
            .replace(/敵全体の強化効果を全て解除（銀フレーム付きを含む）/gm, "Cancels buffs on all targets (including with silver frames)")
            .replace(/敵全体の強化効果を全て解除（銀フレーム付き強化効果を含まない）/gm, "Cancels all buffs on all targets (not including silver frames)")
            .replace(/自身の弱体効果をすべて解除（フレーム付弱体効果は除く）/gm, "Removes all debuffs (excluding debuffs with frames)")
            .replace(/対象の強化効果を全て解除（銀フレーム付き強化効果を含む）/gm, "Cancels targets buffs (including buffs with silver frames)")
            .replace(/対象の強化効果を全て解除（銀フレーム付きを含む）/gm, "Removes all target's buffs (including with silver frames)")
            .replace(/行動順を消失させられない/gm, "Cannot delete turns")
            .replace(/防御力無視/gm, "Ignores DEF ")
            .replace(/コールアビリティ使用時/gm, "When using call ability")
            .replace(/ブレイク時 ブレイク中攻撃時 行動負荷ダウン/gm, "increases turn rate when inflicting Break or attacking target afflicted with Break")
            .replace(/必ずクリティカル/gm, "Guaranteed critical")
            .replace(/必中 行動負荷が無い/gm, "instant turn rate")
            .replace(/BRV乗算後に/gm, "After BRV increase")
            .replace(/受けるBRVダメージを軽減するようになる/gm, "Reduces BRV damage taken")
            .replace(/与えたBRVダメージに応じて自身のHPを回復/gm, "Recovers HP depending on BRV damage dealt")
            .replace(/対象ブレイク時 ブレイク中攻撃時/gm, "When breaking or attacking broken target")
            .replace(/味方全員のBRVを加算/gm, "Grants party BRV")
            .replace(/対象をブレイク/gm, "Breaks target")
            .replace(/自身のHPを回復/gm, "Recover own HP")
            .replace(/味方のBRVを加算/gm, "Increases BRV of allies")
            .replace(/与えたHPダメージに応じて 自身のHP回復/gm, "Heals HP based on HP damage dealt")
            .replace(/自身にBRVを加算/gm, "Increases own BRV")
            .replace(/対象に中確率で/gm, "fair chance of ")
            .replace(/行動負荷ダウン/gm, "increases turn rate")
            .replace(/与えるBRVダメージを[\s]*小アップ/gm, "Increases BRV Damage")
            .replace(/自身の与えるBRVダメージ大アップ/gm, "Adds BRV Damage Up")
            .replace(/自身の受けるBRV加算効果中アップ/gm, "Adds BRV Gains Up")
            .replace(/自身の奪ったBRVを最大BRVを超えて加算する上限中アップ/gm, "Adds Stolen MAX BRV Overflow Up")
            .replace(/自身の加算したBRVを最大BRVを超えて加算する上限中アップ/gm, "Adds Gained MAX BRV Overflow Up")
            .replace(/奪ったBRVを最大BRVを超えて加算する上限/gm, "Increases Stolen MAX BRV Overflow by ")
            .replace(/加算したBRVを最大BRVを超えて加算する上限/gm, "Increases Gain MAX BRV Overflow by ")
            .replace(/(\d+)HITごとに/gm, "Every $1 BRV hits ")
            .replace(/味方全員に加算/gm, " to Party ")
            .replace(/数に応じてBRV威力/gm, " BRV power based on active ")
            .replace(/数に応じて加算量/gm, " based on number active ")
            .replace(/(\[[^\]]*\])への耐性が上昇し/gm, "Increases resist to $1")
            .replace(/HIT数が(\d+)HITに増え/gm, "Increases <BRV> hits to $1")
            .replace(/1ACTION期間延長/gm, " extended by 1 turn")
            .replace(/(\d+)ACTION期間延長/gm, " extended by $1 turns")
            .replace(/1ACTION期間追加/gm, "extends granted buffs by 1 turn")
            .replace(/(\d+)ACTION期間追加/gm, "extends granted buffs by $1 turns")
            .replace(/HIT数が(\d+)HITに変化/gm, "Increases <BRV> hits to $1 ")
            .replace(/自身以外の味方全員に/gm, "Party (except self) ")
            .replace(/以下の効果が追加/gm, " grants effects ")
            .replace(/を(\d+)回行い/gm, " $1 times")
            .replace(/ランダムで1個奪う/gm, "Steals 1 buff")
            .replace(/ランダムで(\d+)個奪う/gm, "Steals $1 buffs")
            .replace(/(自身の)(.+)(に変化)/gm, "$1$3$2")
            .replace(/自身のに変化/gm, "Adds ")
            .replace(/近距離物理/gm, "<Melee> ")
            .replace(/遠距離物理/gm, "<Ranged> ")
            .replace(/物理</gm, "<Melee> ")
            .replace(/魔法/gm, "<Magic> ")
            .replace(/属性/gm, " ") //removes element Attribute
            .replace(/に強化効果/gm, "buff")
            .replace(/弱体効果/gm, "debuff")
            .replace(/防御力/gm, "DEF")
            .replace(/素早さ/gm, "SPD")
            .replace(/初期BRV/gm, "INT BRV")
            .replace(/最大BRV/gm, "MAX BRV")
            .replace(/最大HP/gm, "Max HP")
            .replace(/回避率/gm, "Evade")
            .replace(/対象/gm, " to the target ")
            .replace(/の受けるBRV加算効果/gm, "BRV Gains")
            .replace(/行動負荷も低い/gm, "High Turn Rate")
            .replace(/行動負荷が低い/gm, "High Turn rate")
            .replace(/必中/gm, "guaranteed hit")
            .replace(/自身のBRVを加算し/gm, "Increases BRV")
            .replace(/ブレイク状態を回復し/gm, "Recovers from Break")
            .replace(/身のBRVを加算/gm, "Increases own BRV")
            .replace(/対象にdebuff/gm, "inflicts")
            .replace(/以下の効果が発動/gm, " Grants")
            .replace(/自身buff/gm, "Grants ")
            .replace(/強化効果/gm, "Grants ")
            .replace(/全体/gm, "<AOE> ")
            .replace(/耐性を無視/gm, "Ignore resistance")
            .replace(/(([^・|^\n].+)(の効果小アップ))/gm, "Small increase to $2")
            .replace(/((\[[^\]]*\])の効果の1ACTION期間延長)/gm, "Extends $2 by 1 turn")
            .replace(/((\[[^\]]*\])の効果の(\d+)ACTION期間延長)/gm, "Extends $2 by $3 turns")
            .replace(/から(\d+)ACTION/gm, " for $1 turns")
            .replace(/自身以外の味方/gm, "Party (except self)")
            .replace(/確実に命中/gm, "Guaranteed hit")
            .replace(/(1ACTION)/gm, "1 turn")
            .replace(/((\d+)ACTION)/gm, "$2 turns")
            .replace(/味方全員に/gm, "Adds Party ")
            .replace(/味方全員の/gm, "to all allies ")
            .replace(/味方全員/gm, "to all allies ")
            .replace(/与えた時 /gm, "Increases ")
            .replace(/BRV回復効果/gm, "BRV Regen")
            .replace(/HP回復効果/gm, "HP Regen")
            .replace(/自身以外の味方/gm, "Adds Party (except Self)")
            .replace(/(を(\d+)回行うに変化し)/gm, " $2 times")
            .replace(/クリティカルになる/gm, "becomes critical")
            .replace(/追撃参加時/gm, "During a knock back")
            .replace(/付与される確率/gm, "Chances of being inflicted by ")
            .replace(/極大確率/gm, "Very High Chance of ")
            .replace(/極小確率/gm, "Very Small Chance of ")
            .replace(/小確率/gm, "Small Chance of ")
            .replace(/中確率/gm, "Medium Chance of ")
            .replace(/大確率/gm, "High Chance of ")
            .replace(/HPが回復/gm, "HP Heal")
            .replace(/HP回復上限/gm, "HP Heal limit ")
            .replace(/全体 /gm, "<AOE> ")
            .replace(/全体/gm, "<AOE> ")
            .replace(/(\d+)HIT/gm, "$1-Hit ")
            .replace(/追加攻撃/gm, "Additional Attack")
            .replace(/攻撃した時/gm, "When attacking ")
            .replace(/付与されている時/gm, "When granted ")
            .replace(/ターゲット以外にも/gm, " non-targets ")
            .replace(/攻撃力/gm, "ATK")
            .replace(/攻撃/gm, "Attack")
            .replace(/は除く/gm, " Excludes ")
            .replace(/を行う/gm, " deals")
            .replace(/最終HIT後/gm, " on last hit ")
            .replace(/カウンター/gm, "Counter ")
            .replace(/＋/gm, "+")
            .replace(/ : /gm, ": ")
            .replace(/[　]*・/gm, "\xa0- ")
            .replace(/が/gm, " becomes ")
            .replace(/　-/gm, "\xa0- ")
            .replace(/　+/gm, "\xa0- ")
            .replace(/合計威力も/gm, " potency ")
            .replace(/1回のみ/gm, "only once")
            .replace(/その後/gm, "Then ")
            .replace(/使用後/gm, "After use ")
            .replace(/発動/gm, " triggers")
            .replace(/に変化/gm, " changed to ")
            .replace(/ターゲットに/gm, " to the target ")
            .replace(/威力アップ/gm, "Power Up ")
            .replace(/で追加発動する/gm, " triggered ")
            .replace(/には影響しない/gm, "does not apply")
            .replace(/そのアビリティ/gm, "that ability ")
            .replace(/行動負荷/gm, "Turn Rate")
            .replace(/ブレイクボーナス/gm, "Break Bonus")
            .replace(/効果時間/gm, "extends duration ")
            .replace(/合計/gm, "extends to ")
            .replace(/極小アップ/gm, " Up Very Small")
            .replace(/極大アップ/gm, " Up Very Large")
            .replace(/小アップ/gm, " Up Small")
            .replace(/中アップ/gm, " Up Medium")
            .replace(/大アップ/gm, " Up Large")
            .replace(/極小ダウン/gm, " Down Very Small")
            .replace(/極大ダウン/gm, " Down Very Large")
            .replace(/大ダウン/gm, " Down Very Large")
            .replace(/小ダウン/gm, " Down Small")
            .replace(/中ダウン/gm, " Down Medium")
            .replace(/した後/gm, " after")
            .replace(/を除く/gm, " expect for ")
            .replace(/自身へ/gm, "Self ")
            .replace(/自身に/gm, "Self ")
            .replace(/効果/gm, " effect ")
            .replace(/になり/gm, " becomes ")
            .replace(/および/gm, " and ")
            .replace(/かつ/gm, " and ")
            .replace(/追加/gm, " as well as ")
            .replace(/与える/gm, "dealt ")
            .replace(/アップ/gm, " Up")
            .replace(/単体/gm, " ST ")
            .replace(/自身の/gm, "Self ")
            .replace(/以下の/gm, "")
            .replace(/を1回行う/gm, " 1 time")
            .replace(/を(\d+)回行う/gm, " $1 times")
            .replace(/\]([\s]+):/gm, "]:")
            .replace(/\]:([^\s]+)/gm, "]: $1")
            .replace(/:([^\s])/gm, ": $1")

            //format fixes
            .replace(/の与えるBRVダメージ Up/gm, " BRV Damage Up")
            .replace(/の与えるHPダメージ Up/gm, " HP Damage Up")
            .replace(/>Attack/gm, "> Attack")
            .replace(/Attack\+</gm, "Attack + <")
            .replace(/<BRV> Attack \+ </gm, "<BRV> + <")
            .replace(/Attack\+ st/gm, "Attack + ST")
            .replace(/Attackに変化/gm, "Attack")
            .replace(/Grants Improves/gm, "Improves")
            .replace(/AttackIncreases/gm, "Attack Increases")
            .replace(/\]\[/gm, "] [")
            .replace(/HPダメージ/gm, "HP Damage")
            .replace(/BRVダメージ/gm, "BRV Damage")
            .replace(/付与 becomes/gm, " becomes")
            .replace(/becomes becomes/gm, " becomes")
            .replace(/becomes Grants/gm, " becomes")
            .replace(/turnSelf/gm, "turn Self")
            .replace(/turnsSelf/gm, "turns Self")
            .replace(/の効果追加/gm, "")
            .replace(/（/gm, " (")
            .replace(/）/gm, ") ")
            .replace(/特殊効果/gm, "")
            .replace(/becomes 発動/gm, "")
            .replace(/に変化し/gm, "")
            .replace(/の効果 /gm, "")
            .replace(/通常/gm, "")
            .replace(/する/gm, "")
            .replace(/量/gm, "")
            .replace(/後/gm, "")
            .replace(/前/gm, "")
            .replace(/化/gm, "")
            .replace(/と/gm, "")
            .replace(/て/gm, " ")
            .replace(/で/gm, "")
            .replace(/を/gm, "")
            .replace(/し/gm, "")
            .replace(/の/gm, "")
            .replace(/に/gm, "")
            .replace(/へ/gm, "")
      return (
         replacement
      )
   }
}